import json
from database_search.uniprot import UniprotTaxo

ensembl_ftp_species = [
    "acanthochromis_polyacanthus",
    "accipiter_nisus",
    "ailuropoda_melanoleuca",
    "amazona_collaria",
    "amphilophus_citrinellus",
    "amphiprion_ocellaris",
    "amphiprion_percula",
    "anabas_testudineus",
    "anas_platyrhynchos",
    "anas_platyrhynchos_platyrhynchos",
    "anas_zonorhyncha",
    # "ancestral_alleles",
    "anolis_carolinensis",
    "anser_brachyrhynchus",
    "anser_cygnoides",
    "aotus_nancymaae",
    "apteryx_haastii",
    "apteryx_owenii",
    "apteryx_rowi",
    "aquila_chrysaetos_chrysaetos",
    "astatotilapia_calliptera",
    "astyanax_mexicanus",
    # "astyanax_mexicanus_pachon",
    "athene_cunicularia",
    "balaenoptera_musculus",
    "betta_splendens",
    "bison_bison_bison",
    # "bos_grunniens",
 "30521",
    # "bos_indicus_hybrid",
 "9915",
    "bos_mutus",
    "bos_taurus",
    # "bos_taurus_hybrid",
    "bubo_bubo",
    "buteo_japonicus",
    "caenorhabditis_elegans",
    # "cairina_moschata_domestica",
 "cairina_moschata",
    "calidris_pugnax",
    "calidris_pygmaea",
    "callithrix_jacchus",
    "callorhinchus_milii",
    # "camarhynchus_parvulus",
 "87175",
    "camelus_dromedarius",
    "canis_lupus_dingo",
    "canis_lupus_familiaris",
    # "canis_lupus_familiarisbasenji",
    # "canis_lupus_familiarisboxer",
    # "canis_lupus_familiarisgreatdane",
    # "canis_lupus_familiarisgsd",
    "capra_hircus",
    # "capra_hircus_blackbengal",
    "carassius_auratus",
    "carlito_syrichta",
    "castor_canadensis",
    "catagonus_wagneri",
    "catharus_ustulatus",
    "cavia_aperea",
    "cavia_porcellus",
    "cebus_imitator",
    "cercocebus_atys",
    "cervus_hanglu_yarkandensis",
    "chelonoidis_abingdonii",
    "chelydra_serpentina",
    "chinchilla_lanigera",
    "chlorocebus_sabaeus",
    "choloepus_hoffmanni",
    "chrysemys_picta_bellii",
    "chrysolophus_pictus",
    "ciona_intestinalis",
    "ciona_savignyi",
    "clupea_harengus",
    "colobus_angolensis_palliatus",
    "corvus_moneduloides",
    "cottoperca_gobio",
    "coturnix_japonica",
 "cricetulus_griseus",
    # "cricetulus_griseus_chok1gshd",
    # "cricetulus_griseus_crigri",
    # "cricetulus_griseus_picr",
    "crocodylus_porosus",
    "cyanistes_caeruleus",
    "cyclopterus_lumpus",
    "cynoglossus_semilaevis",
    "cyprinodon_variegatus",
    "cyprinus_carpio_carpio",
    # "cyprinus_carpio_germanmirror",
    # "cyprinus_carpio_hebaored",
    # "cyprinus_carpio_huanghe",
    "danio_rerio",
    "dasypus_novemcinctus",
    "delphinapterus_leucas",
    "denticeps_clupeoides",
    "dicentrarchus_labrax",
    "dipodomys_ordii",
    "dromaius_novaehollandiae",
    "drosophila_melanogaster",
    "echeneis_naucrates",
    "echinops_telfairi",
    "electrophorus_electricus",
    "eptatretus_burgeri",
    "equus_asinus",
    "equus_caballus",
    "erinaceus_europaeus",
    "erpetoichthys_calabaricus",
    # "erythrura_gouldiae",
 "44316",
    "esox_lucius",
    "falco_tinnunculus",
    "felis_catus",
    "ficedula_albicollis",
    "fukomys_damarensis",
    "fundulus_heteroclitus",
    "gadus_morhua",
    "gallus_gallus",
    "gambusia_affinis",
    "gasterosteus_aculeatus",
    "geospiza_fortis",
    "gopherus_agassizii",
    "gopherus_evgoodei",
    "gorilla_gorilla",
    "gouania_willdenowi",
    "haplochromis_burtoni",
 "heterocephalus_glaber",
    # "heterocephalus_glaber_female",
    # "heterocephalus_glaber_male",
    "hippocampus_comes",
    "homo_sapiens",
    "hucho_hucho",
    "ictalurus_punctatus",
    "ictidomys_tridecemlineatus",
    "jaculus_jaculus",
    "junco_hyemalis",
    "kryptolebias_marmoratus",
    "labrus_bergylta",
    "larimichthys_crocea",
    "lates_calcarifer",
    "laticauda_laticaudata",
    "latimeria_chalumnae",
    "lepidothrix_coronata",
    "lepisosteus_oculatus",
    "leptobrachium_leishanense",
    # "lonchura_striata_domestica",
 "40157",
    "loxodonta_africana",
    "lynx_canadensis",
    "macaca_fascicularis",
    "macaca_mulatta",
    "macaca_nemestrina",
    "malurus_cyaneus_samueli",
    "manacus_vitellinus",
    "mandrillus_leucophaeus",
    "marmota_marmota_marmota",
    "mastacembelus_armatus",
    "maylandia_zebra",
    "meleagris_gallopavo",
    "melopsittacus_undulatus",
    "meriones_unguiculatus",
    "mesocricetus_auratus",
    "microcebus_murinus",
    "microtus_ochrogaster",
    "mola_mola",
    "monodelphis_domestica",
    "monodon_monoceros",
    "monopterus_albus",
    "moschus_moschiferus",
    "mus_caroli",
    "mus_musculus",
    # "mus_musculus_129s1svimj",
    # "mus_musculus_aj",
    # "mus_musculus_akrj",
    # "mus_musculus_balbcj",
    # "mus_musculus_c3hhej",
    # "mus_musculus_c57bl6nj",
    # "mus_musculus_casteij",
    # "mus_musculus_cbaj",
    # "mus_musculus_dba2j",
    # "mus_musculus_fvbnj",
    # "mus_musculus_lpj",
    # "mus_musculus_nodshiltj",
    # "mus_musculus_nzohlltj",
    # "mus_musculus_pwkphj",
    # "mus_musculus_wsbeij",
    "mus_pahari",
    "mus_spicilegus",
    "mus_spretus",
    "mustela_putorius_furo",
    "myotis_lucifugus",
    "myripristis_murdjan",
    "naja_naja",
    "nannospalax_galili",
    "neogobius_melanostomus",
    "neolamprologus_brichardi",
    "neovison_vison",
    "nomascus_leucogenys",
    "notamacropus_eugenii",
    "notechis_scutatus",
    "nothobranchius_furzeri",
    "nothoprocta_perdicaria",
    "numida_meleagris",
    "ochotona_princeps",
    "octodon_degus",
    "oncorhynchus_kisutch",
    "oncorhynchus_mykiss",
    "oncorhynchus_tshawytscha",
    "oreochromis_aureus",
    "oreochromis_niloticus",
    "ornithorhynchus_anatinus",
    "oryctolagus_cuniculus",
    "oryzias_javanicus",
    "oryzias_latipes",
    # "oryzias_latipes_hni",
    # "oryzias_latipes_hsok",
    "oryzias_melastigma",
    "oryzias_sinensis",
    "otolemur_garnettii",
    "otus_sunia",

    "ovis_aries",
    # "ovis_aries_rambouillet",
    "pan_paniscus",
    "pan_troglodytes",
    "panthera_leo",
    "panthera_pardus",
    "panthera_tigris_altaica",
    "papio_anubis",
    "parambassis_ranga",
    "paramormyrops_kingsleyae",
    "parus_major",
    "pavo_cristatus",
    "pelodiscus_sinensis",
    "pelusios_castaneus",
    "periophthalmus_magnuspinnatus",
    "peromyscus_maniculatus_bairdii",
    "petromyzon_marinus",
    "phascolarctos_cinereus",
    "phasianus_colchicus",
    "phocoena_sinus",
 "9755", 
    # "physeter_catodon",
    "piliocolobus_tephrosceles",
    "podarcis_muralis",
    "poecilia_formosa",
    "poecilia_latipinna",
    "poecilia_mexicana",
    "poecilia_reticulata",
    "pogona_vitticeps",
    "pongo_abelii",
    "procavia_capensis",
    "prolemur_simus",
    "propithecus_coquereli",
    "pseudonaja_textilis",
    "pteropus_vampyrus",
    "pundamilia_nyererei",
    "pygocentrus_nattereri",

    "rattus_norvegicus",
    # "rattus_norvegicus_shrspbbbutx",
    # "rattus_norvegicus_shrutx",
    # "rattus_norvegicus_wkybbb",
    "rhinolophus_ferrumequinum",
    "rhinopithecus_bieti",
    "rhinopithecus_roxellana",
    "saccharomyces_cerevisiae",
    "saimiri_boliviensis_boliviensis",
    "salarias_fasciatus",
    "salmo_salar",
    "salmo_trutta",
    "salvator_merianae",
    "sander_lucioperca",
    "sarcophilus_harrisii",
    "sciurus_vulgaris",
    "scleropages_formosus",
    "scophthalmus_maximus",
    "serinus_canaria",
    "seriola_dumerili",
    "seriola_lalandi_dorsalis",
    "sinocyclocheilus_anshuiensis",
    "sinocyclocheilus_grahami",
    "sinocyclocheilus_rhinocerous",
    "sorex_araneus",
    "sparus_aurata",
    "spermophilus_dauricus",
    "sphaeramia_orbicularis",
    "sphenodon_punctatus",
    # "stachyris_ruficeps",
 "181631",
    "stegastes_partitus",
    "strigops_habroptila",
    "strix_occidentalis_caurina",
    "struthio_camelus_australis",
    "suricata_suricatta",
    "sus_scrofa",
    # "sus_scrofa_bamei",
    # "sus_scrofa_berkshire",
    # "sus_scrofa_hampshire",
    # "sus_scrofa_jinhua",
    # "sus_scrofa_landrace",
    # "sus_scrofa_largewhite",
    # "sus_scrofa_meishan",
    # "sus_scrofa_pietrain",
    # "sus_scrofa_rongchang",
    # "sus_scrofa_tibetan",
    # "sus_scrofa_usmarc",
    # "sus_scrofa_wuzhishan",
    "taeniopygia_guttata",
    "takifugu_rubripes",
 "2587831",
    # "terrapene_carolina_triunguis",
    "tetraodon_nigroviridis",
    "theropithecus_gelada",
    "tupaia_belangeri",
    "tursiops_truncatus",
    "urocitellus_parryii",
    "ursus_americanus",
    "ursus_maritimus",
    "ursus_thibetanus_thibetanus",
    "varanus_komodoensis",
    "vicugna_pacos",
    "vombatus_ursinus",
    "vulpes_vulpes",
    "xenopus_tropicalis",
    "xiphophorus_couchianus",
    "xiphophorus_maculatus",
    "zalophus_californianus",
    "zonotrichia_albicollis",
    "zosterops_lateralis_melanops"
]


big_dict = {}

small_dict = {
    '30521':  'bos_grunniens',
    '9915': 'bos_indicus_hybrid',
    'cairina moschata': 'cairina_moschata_domestica',
    '87175': 'camarhynchus_parvulus',
    'cricetulus griseus': 'cricetulus_griseus_chok1gshd',
    '44316': 'erythrura_gouldiae',
    'heterocephalus glaber': 'heterocephalus_glaber_female',
    '40157': 'lonchura_striata_domestica',
    '9755': 'physeter_catodon',
    '181631': 'stachyris_ruficeps',
    '2587831': 'terrapene_carolina_triunguis',
}

for species in ensembl_ftp_species:
    species = species.replace('_', ' ')
    uniprot_taxo = UniprotTaxo(species)
    taxo = uniprot_taxo.get_taxonomy()
    
    if species in ['30521', '9915', 'cairina moschata domestica', '87175', 'cricetulus griseus', '44316', 'heterocephalus glaber', '40157', '9755', '181631', '2587831']:
        ensembl_scientific_name = small_dict[species]
        ensembl_scientific_name = ensembl_scientific_name.replace(' ', '_')
    else:
        ensembl_scientific_name = species.replace(' ', '_')
    
    ensembl_taxid = taxo['taxonId']
    for lineage in taxo['lineage']:
        
        if lineage['taxonId'] not in big_dict:
            big_dict[lineage['taxonId']] = {'scientific_names': [], 'taxids': []}
            
        big_dict[lineage['taxonId']]['scientific_names'].append(ensembl_scientific_name)
        big_dict[lineage['taxonId']]['taxids'].append(ensembl_taxid)
        
        
        if ensembl_scientific_name == 'cricetulus_griseus_chok1gshd':
            big_dict[lineage['taxonId']]['scientific_names'].append('cricetulus_griseus_crigri')
            big_dict[lineage['taxonId']]['scientific_names'].append('cricetulus_griseus_picr')
            big_dict[lineage['taxonId']]['taxids'].append(ensembl_taxid)
            big_dict[lineage['taxonId']]['taxids'].append(ensembl_taxid)
   
        if ensembl_scientific_name == 'heterocephalus_glaber_female':
            big_dict[lineage['taxonId']]['scientific_names'].append('heterocephalus_glaber_male')
            big_dict[lineage['taxonId']]['taxids'].append(ensembl_taxid)
        
with open('ensembl_taxo.json', 'w') as json_file:
    json.dump(big_dict, json_file, indent=4)

