name: br
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - xmltodict=0.13.0  
  - augustus=3.5
  - busco=5.7.1
  - prokka=1.14.6
  - blat=35
  - fastp=0.23.4
  - bowtie2=2.5.4  
  - megahit=1.2.9
  - cd-hit=4.8.1
  - matplotlib=3.9.2
  - ncbi-datasets-cli=17.1.0    
  - psutil==6.0.0
  - pysradb=2.2.2
  - pip
  - pip:
      - bcrypt==4.2.0
      - beautifulsoup4==4.13.3
      - bidict==0.23.1
      - blinker==1.9.0
      - bs4==0.0.2
      - click==8.1.8
      - eventlet==0.37.0
      - flask==3.0.3
      - flask-cors==4.0.1
      - flask-socketio==5.3.6
      - greenlet==3.1.1
      - gunicorn==23.0.0
      - h11==0.14.0
      - importlib-metadata==8.6.1
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - pymongo==4.8.0
      - python-engineio==4.11.2
      - python-socketio==5.12.1
      - simple-websocket==1.1.0
      - soupsieve==2.6
      - typing-extensions==4.12.2
      - werkzeug==3.1.3
      - wsproto==1.2.0
      - xlsxwriter==3.2.0
